services:
  #  Nginx server configuration
  nginx:
    container_name: nginx-server
    image: nginx:stable
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8000:80'
    depends_on:
      - application-one
      - application-two
  #  PostgreSQL database configuration
  postgres:
    container_name: postgres-database
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: forum-hub-alura-challenge
    ports:
      - '5432:5432'
  #  Redis cache database configuration
  redis:
    container_name: redis-cache-database
    restart: always
    image: redis:7.4.1
    ports:
      - '6379:6379'
  #  Applications configurations
  application-one: &app
    container_name: application-instance-one
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/forum-hub-alura-challenge?currentSchema=public
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123
    ports:
      - '8080'
    depends_on:
      - postgres
      - redis
  application-two:
    <<: *app
    container_name: application-instance-two
