spring:
  application:
    name: forum-hub-alura-challenge
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  cache:
    type: redis
    redis:
      time-to-live: 5m
  data:
    jdbc:
      dialect: postgresql
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
  docker:
    compose:
      enabled: false
